### ISSUE TITLE
Request: Ability to delete every item and automatically go onto next page

### ISSUE THREAD

**Issue by poyono** [alexdelorenzo/delete_scrobbles#1]
Hey, thanks for this, it's fantastic! 

I was wondering if there's a way to select every track as I am currently just trying to purge my entire last.fm history. Also, I wanted to ask if there is some way this could auto refresh the page or move onto the next section of the list to be able to delete mass items automatically. This would really only be useful in my use case where I want to delete everything probably but it could be useful.

I tried to do the above things myself but I'm useless really. The refreshing may be possible using the `secondary-nav-item--overview` button but again I am useless.

Thank you in advance and no worries if you aren't able to do this or it's a waste of your time.

**Comment by alexdelorenzo** [comment]
Hey, thanks for the suggestion. This was something I was looking into, but didn't implement. Since there's interest, I'll add this feature and ping you back when I do :)

**Comment by alexdelorenzo** [comment]
Check out the latest script in the `main` branch, @poyono. I added the feature you requested :)

Just make sure you set `ALL_PAGES` to `true`, and the script should cycle through your library. If `DELETE_MATCHING` is set to an empty string, it will mark every scrobble for deletion.

Like so:
```javascript
const DELETE_MATCHING = "";
const ALL_PAGES = true;
```

**Comment by poyono** [comment]
> Check out the latest script in the `main` branch, @poyono. I added the feature you requested :)
> 
> Just make sure you set `ALL_PAGES` to `true`, and the script should cycle through your library. If `DELETE_MATCHING` is set to an empty string, it will mark every scrobble for deletion.
> 
> Like so:
> ```javascript
> const DELETE_MATCHING = "";
> const ALL_PAGES = true;
> ```

This is awesome! I'll check it out later. Thank you!

**Comment by alexdelorenzo** [comment]
Glad it worked out for you! I'm going to close this issue, feel free to open it or comment if you encounter an issue with this update.
